; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32cam]
platform = espressif32@3.5.0
board = esp32cam
board_build.partitions = min_spiffs.csv
framework = arduino
monitor_speed = 115200
lib_deps = 
	ayushsharma82/AsyncElegantOTA@^2.2.7
	me-no-dev/AsyncTCP@^1.1.1
	bblanchon/ArduinoJson@^6.18.5
	robtillaart/Max44009@^0.5.0
	dantudose/MAX44009 library@^1.0.1
	sv-zanshin/BME680@^1.0.12
	fastled/FastLED@^3.4.0
	me-no-dev/ESP Async WebServer@^1.2.3
	arduino-libraries/NTPClient@^3.1.0
	; https://github.com/s00500/ESPUI.git#a958feb152089dc54d6576c442f3eeb26ab79fb5
	https://github.com/s00500/ESPUI.git#0f3a808e9e47c4a8d5ea02a2dd3f24557990095f
	alanswx/ESPAsyncWiFiManager@^0.31
	; yoursunny/esp32cam@^0.0.20220215
